name:                owntracker
version:             0.1.0.0
github:              "dustin/owntracker"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/owntracker#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- aeson
- text
- lens
- time
- influxdb
- containers
- optparse-applicative

executables:
  owntracker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
